MODEL:
  META_ARCHITECTURE: "SSD"
  WEIGHT: "vgg16ssd_torch.pkl"
  BACKBONE:
    CONV_BODY: "VGG16-SSD"
  SSD:
    INPUT_SIZE: 300
    BOX_HEAD:
      PREDICTOR: "SSDHead"
      NUM_CLASSES: 81
DATASETS:
  TRAIN: ("coco_2014_train", "coco_2014_valminusminival")
  TEST: ("coco_2014_minival",)
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 32
  CHECKPOINT_PERIOD: 30000
TEST:
  IMS_PER_BATCH: 8