MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/home/iim321/.torch/models/vgg16_torch.pkl"
  BACKBONE:
    CONV_BODY: "VGG16"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 14
    POOLER_SCALES: (0.0625,)
    POOLER_SAMPLING_RATIO: 0
    FEATURE_EXTRACTOR: "FastRCNNROIFeatureExtractor"
    PREDICTOR: "FastRCNNPredictor"
    NUM_CLASSES: 81
DATASETS:
  TRAIN: ("coco_2014_train", "coco_2014_valminusminival")
  TEST: ("coco_2014_minival",)
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 2
  CHECKPOINT_PERIOD: 3000
TEST:
  IMS_PER_BATCH: 2